### ISSUE TITLE
Analytics testnet does not work

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-analytics#260]
<img width="1298" alt="Screen Shot 2020-07-10 at 7 49 17 PM" src="https://user-images.githubusercontent.com/989846/87214969-7df9a200-c2e6-11ea-90f5-1be58f4cd3ef.png">

**Comment by Madongming** [comment]
Because the mysqldb on testnet, the primary key of the action_history table is receipt_hash, but the code is ‘action_hash’. The query where condition is action_hash, there is no index, so it is very slow. I manually added the index action_hash_index for  the action_hash, but it can't be the primary key, because the the primary key(receipt_hash) already exists. But the effect is ok.
